### ISSUE TITLE
error in whisper_model_sm.deploy(

### ISSUE THREAD

**Issue by Guneetsinghtuli** [aws-samples/whisper-audio-inference-for-amazon-sagemaker#4]
FileNotFoundError: [Errno 2] No such file or directory: 'src'

**Comment by lukerhansen** [comment]
Hi! I am running into this same issue. Do you have any tips for how to avoid it?

**Comment by Guneetsinghtuli** [comment]
Hi @lukerhansen, If you are using SageMaker Studio you need to create a folder names src in the root location (Where your notebook is present)
Exactly the same way as they have kept the src
